workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 10
    environment:
      java: 11
      vars:
        PACKAGE_NAME: "com.example.hairstyle"
    scripts:
      - name: Capacitor Android Build
        script: |
          npm install -g @capacitor/cli
          npm install
          npx cap add android
          npx cap sync android
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
