workflows:
  android-build:
    name: Build Android APK
    environment:
      flutter: stable
      android_signing:
        keystore_reference: null
      vars:
        PACKAGE_NAME: "com.example.hairstyle"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/android
          npx cap sync
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - "youremail@example.com"
